### ISSUE TITLE
Analyzer for Should().Equals()?

### ISSUE THREAD

**Issue by bordecal** [fluentassertions/fluentassertions.analyzers#94]
Use of `actual.Should().Equals(expected)` (which is not an assertion at all) is perhaps the single most serious recurrent error I tend to see with FluentAssertions use.  Would an analyzer to detect this construct fit with the goals for this project?

_N.B._: To be honest, the fact that there isn't already an analyzer for this (or apparently even an existing issue requesting its addition) strikes me as sufficiently odd that I'm wondering if I'm missing some other mechanism that would detect this problem.  If such a beastie does exist, an analyzer would presumably be unnecessary, but a documentation update to increase its visibility might be helpful...

**Comment by wilka** [comment]
@bordecal it's not just you, I've seen this a lot as well. 

Instead of opening an issue about this I started trying to add it myself (I thought it would be more helpful to send a PR than just open an issue), but I got distracted before getting very far so it's been stuck on my todo list for ages.

I should have opened an issue about it a long time ago :)

**Comment by Meir017** [comment]
This makes a lot of sense. I just started this project based on the fluentassertions best practices
